name:                hs
version:             0.1.0.0
github:              "githubuser/hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- loop
- repa
- async


library:
  source-dirs: src

executables:
  hs-exe:
    main:                MVector.hs
    source-dirs:         app
    ghc-options:
    - -main-is MVector
    - -threaded
    - -rtsopts
    dependencies:
    - hs

  hs-i-exe:
    main:                Immutable.hs
    source-dirs:         app
    ghc-options:
    - -main-is Immutable
    - -threaded
    dependencies:
    - hs

  hs-p-exe:
    main:                Repa.hs
    source-dirs:         app
    ghc-options:
    - -main-is Repa
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N8"'
    dependencies:
    - hs

  hs-a-exe:
    main:                Async.hs
    source-dirs:         app
    ghc-options:
    - -main-is Async
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-N12"'
    dependencies:
    - hs
tests:
  hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - hs
